### ISSUE TITLE
helps with right zlib.h 

### ISSUE THREAD

**Issue by DevX-Cipher** [wargio/vitatool#2]
trying to compile this and says cant find zlib.h file something isnt right

**Comment by wargio** [comment]
install zlib (devel/dev) on your system

**Comment by DevX-Cipher** [comment]
I already have it in the sdk it’s right there but fails for someone saying
it can’t find it

**Comment by wargio** [comment]
nono. it has to be installed on the system (host)

**Comment by wargio** [comment]
which OS do you have?

**Comment by DevX-Cipher** [comment]
ive tried using linux mac osx and even minGw whiches is where i compile all of any projects

**Comment by modz2014** [comment]
ok i fixed this issue but when trying to use these in anyway gett error 0x000007b

**Comment by wargio** [comment]
did you solve?
